
- name: Wipe app
  ansible.builtin.import_tasks: 01-wipe.yml
  when: app_full_wipe | bool
  tags: 
    - wipe
    - deploy

- name: Deploy app
  tags: deploy
  block:
    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Create app directory
      ansible.builtin.file:
        path: "{{ app_path }}"
        state: directory

    - name: Template a docker file
      ansible.builtin.template:
        src: docker-compose.yml.j2
        dest: "{{ app_path }}/docker-compose.yml"

    - name: Start all services
      community.docker.docker_compose:
        project_src: "{{ app_path }}"
        state: present
        pull: true      
