name: app_go

on:
  push:
    paths:
      - 'app_go/**'
      - '.github/workflows/app_go.yaml'

defaults:
  run:
    working-directory: app_go

jobs:
  docs:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v2.0.0
        with:
          failure-threshold: error
          dockerfile: 'app_go/Dockerfile'
      - name: Lint Dockerfile Multistage
        uses: hadolint/hadolint-action@v2.0.0
        with:
          failure-threshold: error
          dockerfile: 'app_go/Dockerfile.multistage'
      - name: Lint Markdown
        uses: nosborn/github-action-markdown-cli@v3.0.1
        with:
          files: .

  code:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: app_go
      - name: Build
        run: go build -v .
      - name: Test
        run: go test -v .

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: snyk/actions/setup@master
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13'
      - name: Snyk monitor
        continue-on-error: true
        run: |
          snyk test --sarif-file-output=snyk.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: app_go/snyk.sarif

  deploy:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    needs: [docs, code, security]
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: app_go
          file: app_go/Dockerfile.multistage
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/go_kremlin_chimes:latest
